name: Deploy to 'Github Pages'
on:
    workflow_call:

jobs:
    deploy_to_github_pages:
        runs-on: [ubuntu-latest]
        name: Deploy to 'Github pages'
        permissions:
            pages: write
            id-token: write
        environment:
            name: github-pages
            url: ${{ steps.deploy_pages.outputs.page_url }}
        steps:
            - uses: actions/deploy-pages@v4
              id: deploy_pages

            - run: echo ${{ steps.deploy_pages.outputs.page_url }}
