name: Process discussion comment

on:
    discussion_comment:
        types: [created]

jobs:
    process_comment:
        permissions:
            discussions: write
        runs-on: ubuntu-latest
        steps:
            - name: Process the comment
              run: |
                  echo "Comment body: ${{ github.event.comment.body }}"
                  echo "Author: ${{ github.event.comment.user.login }}"
                  echo "Discussion title: ${{ github.event.discussion.title }}"

            - name: Delete the comment
              run: |
                  gh api graphql -f query='
                      mutation($id: ID!) {
                      deleteDiscussionComment(input: {id: $id}) {
                          comment { id }
                      }
                      }
                  ' -f id="$COMMENT_NODE_ID"
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  COMMENT_NODE_ID: ${{ github.event.comment.node_id }}
